#!/bin/bash
#Labs

echo "LAB1 - Comandos básicos para navegar"
echo "Ingresa el comando de acuerdo a la instrucción"
echo "Si el comando es correcto se mostrará el output"

while true
do
        echo "1. Verificar el directorio actual"
        read respuesta
        if [ $respuesta = "pwd" ]
        then
                $respuesta
                break
   fi
done
while true
do
        echo "2. Crear la carpeta "dir1" con el parametro "verbose""
        read respuesta2
        if [[ $respuesta2 = "mkdir -v dir1" ]]
        then
                $respuesta2
                break
   fi
done
while true
do
        echo "3. Crear la carpeta "dir2" con el parametro "verbose""
        read respuesta3
        if [[ $respuesta3 = "mkdir -v dir2" ]]
        then
                $respuesta3
                break
fi
done
while true
do
        echo "4. Crear la carpeta "dir3" dentro de "dir2" con el parametro "verbose""
        read respuesta4
        if [[ $respuesta4 = "mkdir -v dir2/dir3" ]]
        then
                $respuesta4
                break
fi
done
while true
do
        echo "5. Crear la carpeta "dir4" dentro de "dir3" con el parametro "verbose""
        read respuesta5
        if [[ $respuesta5 = "mkdir -v dir2/dir3/dir4" ]]
        then
                $respuesta5
                break
fi
done
while true
do
        echo "6. Lista el contenido del directorio actual"
        read respuesta6
        if [ $respuesta6 = "ls" ]
        then
                $respuesta6
                break
fi
done
while true
do
        echo "7. Lista todo los archivos en la carpeta actual de forma recursiva"
        read respuesta7
        if [[ $respuesta7 = "ls -R" ]]
        then
                $respuesta7
                break
fi
done
while true
do
        echo "8. Cambiarse a la carpeta dir2"
        read respuesta8
        if [[ $respuesta8 = "cd dir2" ]]
        then
                $respuesta8
                break
fi
done
while true
do
        echo "9. Regresa a la carpeta anterior"
        read respuesta9
        if [[ $respuesta9 = "cd -" ]]
        then
                $respuesta9
                break
fi
done
while true
do
        echo "10. Cambiate a la carpeta home del usuario actual"
        read respuesta10
        if [ $respuesta10 = "cd" ]
        then
                $respuesta10
                break
fi
done
echo -e "Felicidades, acabaste el primer lab\n"
